// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4311.mess;



import com.ni.vision.NIVision;
import com.ni.vision.NIVision.DrawMode;
import com.ni.vision.NIVision.Image;
import com.ni.vision.NIVision.ShapeMode;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.vision.AxisCamera;

import org.usfirst.frc4311.mess.commands.*;
import org.usfirst.frc4311.mess.subsystems.*;



/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {
	public static OI oi;
	public static Robotdrive robotdrive;
	public static Subsystem grabber;
	public static Subsystem lifter;
	public static Command autonomousCommand;
	public static Command grab;
	public static Command lift;
	//int session;
    //Image frame;
    //AxisCamera camera;

 	/**
	 * This function is run when the robot is first started up and should be
	 * used for any initialization code.
	 */
	public void robotInit() {
		RobotMap.init();
		robotdrive = new Robotdrive();
		// OI must be constructed after subsystems. If the OI creates Commands 
		//(which it very likely will), subsystems are not guaranteed to be 
		// constructed yet. Thus, their requires() statements may grab null 
		// pointers. Bad news. Don't move it.
		oi = new OI();
		//frame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_RGB, 0);

        // open the camera at the IP address assigned. This is the IP address that the camera
        // can be accessed through the web interface.
		AxisCamera camera;
        camera = new AxisCamera("localhost");
        System.out.println(camera.getMaxFPS());
        
		// instantiate the command used for the autonomous period
		autonomousCommand = new AutonomousCommand();
	}

	/**
	 * This function is called when the disabled button is hit.
	 * You can use it to reset subsystems before shutting down.
	 */
	public void disabledInit(){

	}

	public void disabledPeriodic() {
		Scheduler.getInstance().run();
	}

	public void autonomousInit() {
		// schedule the autonomous command (example)
		if (autonomousCommand != null) autonomousCommand.start();
	}

	/**
	 * This function is called periodically during autonomous
	 */
	public void autonomousPeriodic() {
		Scheduler.getInstance().run();
	}

	public void teleopInit() {
		// This makes sure that the autonomous stops running when
		// teleop starts running. If you want the autonomous to 
		// continue until interrupted by another command, remove
		// this line or comment it out.
		if (autonomousCommand != null) autonomousCommand.cancel();
	}

	/**
	 * This function is called periodically during operator control
	 */
	public void teleopPeriodic() {
		Scheduler.getInstance().run();
		//NIVision.Rect rect = new NIVision.Rect(10, 10, 100, 100);while (isOperatorControl() && isEnabled())
		RobotMap.robotdriveRobotDrive41.setSafetyEnabled(true);
		RobotMap.lifterRobotDrive21.setSafetyEnabled(true);
		{
			if (OI.joystickButton2.get()== true){
				RobotMap.grabberSolenoidleft.set(true);
				RobotMap.grabberSolenoidright.set(true);
			}
			
			if  (OI.joystickButton3.get()== true){
				RobotMap.grabberSolenoidleft.set(true);
				RobotMap.grabberSolenoidright.set(true);
			}
			
			else {
				RobotMap.grabberSolenoidleft.set(false);
				RobotMap.grabberSolenoidright.set(false);
			}
			if (OI.joystickButton1.get()== true)
			{ new HalfSpeed(); 
				 
					RobotMap.lifterRobotDrive21.tankDrive(oi.joystick2.getY()/2,oi.joystick2.getY()/2);
				
				}
			
		        
		   //         camera.getImage(frame);
		   //         NIVision.imaqDrawShapeOnImage(frame, frame, rect,
		     //               DrawMode.DRAW_VALUE, ShapeMode.SHAPE_OVAL, 0.0f);

		    //        CameraServer.getInstance().setImage(frame);
			
			// Use the joystick2 y axis for lateral movement, joystick1 Y axis for forward movement, and joystick1 x axis for rotation.
			// This sample does not use field-oriented drive, so the gyro input is set to zero.
			
			else{
				RobotMap.robotdriveRobotDrive41.mecanumDrive_Cartesian(oi.joystick2.getX()/-2, oi.joystick1.getX()/2, oi.joystick1.getY()/2, 0);
				RobotMap.lifterRobotDrive21.tankDrive(oi.joystick2.getY()/2,oi.joystick2.getY()/2);
				}
		Timer.delay(0.005);	// wait 5ms to avoid hogging CPU cycles
		}
	}
	
	/**
	 * This function is called periodically during test mode
	 */
	public void testPeriodic() {
		LiveWindow.run();
	}
}
