// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4311.mess.subsystems;
import org.usfirst.frc4311.mess.RobotMap;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;

public class Robotdrive extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rbc = RobotMap.robotdriverbc; /** Right back controller */
    SpeedController lbc = RobotMap.robotdrivelbc; /** Left back controller */
    SpeedController lfc = RobotMap.robotdrivelfc; /** Left front controller */
    SpeedController rfc = RobotMap.robotdriverfc; /** Right front controller */
    RobotDrive robotDrive41 = RobotMap.robotdriveRobotDrive41;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

