// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4311.mess.commands;
import org.usfirst.frc4311.mess.OI;
import org.usfirst.frc4311.mess.RobotMap;
import edu.wpi.first.wpilibj.command.Command;

public class  SpeedModifier extends Command {
	public Speeds speed;

	public SpeedModifier(Speeds speed) {
		this.speed = speed;
	}

	@Override
	protected void initialize() {
		
	}

	@Override
	protected void execute() {
		switch (speed) {
		case QUARTER_SPEED: System.out.println("Quarter Speed"); this.setRobotSpeed(3); break;
		case HALF_SPEED: System.out.println("Half Speed"); this.setRobotSpeed(2); break;
		case SPRINT: System.out.println("Don't"); this.setRobotSpeed(1); break;
		}
	}

	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	protected void end() {
		// TODO Auto-generated method stub
	}

	@Override
	protected void interrupted() {
		// TODO Auto-generated method stub	
	}

	/**
	 * Change speed of robot to passed integer
	 * @param speed Speed passed to change the robot to (only 1, 2, 3)
	 */
	private void setRobotSpeed(int speed) {
		OI oi = new OI(); //Operator Interface
		double xVal = oi.joystick2.getX() / speed;
		double yVal = oi.joystick1.getY() / speed;

		RobotMap.robotdriveRobotDrive41.mecanumDrive_Cartesian((xVal * -1), yVal, oi.joystick1.getY() / speed, 0);
		RobotMap.lifterRobotDrive21.tankDrive(yVal, yVal);
		//RobotMap.robotdriveRobotDrive41.mecanumDrive_Cartesian(oi.joystick2.getX()/-2, oi.joystick1.getX()/2, oi.joystick1.getY()/2, 0);
		//RobotMap.lifterRobotDrive21.tankDrive(oi.joystick2.getY()/2,oi.joystick2.getY()/2);
	}
}
