// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4311.mess.commands;
import edu.wpi.first.wpilibj.command.Command;

public class  SpeedModifier extends Command {
	public Speeds speed;
	
	public SpeedModifier(Speeds speed) {
		this.speed = speed;
	}

	@Override
	protected void initialize() {
		switch (speed) {
		case QUARTER_SPEED: System.out.println("Quarter Speed"); break;
		case HALF_SPEED: System.out.println("Half Speed"); break;
		case SPRINT: System.out.println("Don't"); break;
		}
	}

	@Override
	protected void execute() {
		// TODO Auto-generated method stub
	}

	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	protected void end() {
		// TODO Auto-generated method stub
	}

	@Override
	protected void interrupted() {
		// TODO Auto-generated method stub	
	}
}
